#!/usr/bin/env python3
"""Generate numbers.tex from the bundle's results.json + datasets_manifest.json — every number the
manuscript prints is machine-derived from the same run the reproduction contract re-executes; the
script fails loudly if any needed key is missing, so no printed number can drift from the run."""
import json, math, os
HERE = os.path.dirname(os.path.abspath(__file__))
res = json.load(open(os.path.join(HERE, '..', 'model_bundle', 'results.json')))
man = json.load(open(os.path.join(HERE, '..', 'datasets_manifest.json')))

def days(deg): return abs(deg) * 365.25 / 360.0

def ptex(p): return f"p < 10^{{{math.ceil(math.log10(p))}}}" if p < 1e-3 else f"p = {p:.4f}"

DS = ["ImageTopics", "NewsTopics", "ShopTopics", "YouTubeTopics"]
P = res["pooled"]
m = {
    'nMonths': f"{man['months']}", 'winStart': man['window'][0], 'winEnd': man['window'][1],
    'nTotal': f"{P['n']}",
    'poolAgree': f"{P['agree_pct']:.1f}", 'poolAdj': f"{P['agree_adjacent_pct']:.1f}",
    'poolLift': f"{P['lift']:.2f}", 'poolLogP': f"{P['log10_p_binomial_optimistic']:.0f}",
    'poolClusters': f"{P['clusters_n']}", 'poolClusterAgree': f"{P['cluster_agree_pct']:.1f}",
    'poolPermZ': f"{P['perm_z']:.1f}", 'poolPermP': ptex(P['perm_p']),
    'poolOffset': f"{P['mean_signed_offset_deg']:.1f}",
    'poolOffsetDays': f"{days(P['mean_signed_offset_deg']):.0f}",
    'poolOffsetR': f"{P['offset_R']:.2f}",
    'poolMedAbs': f"{P['median_abs_offset_deg']:.1f}",
    'poolMedAbsDays': f"{days(P['median_abs_offset_deg']):.0f}",
    'poolRotMax': f"{P['rotation_max_pct']:.1f}", 'poolRotMaxK': f"{P['rotation_max_k']}",
    'poolRotRest': f"{P['rotation_mean_excl_best_pct']:.1f}",
    'poolRtwo': f"{P['mean_train_r2']:.2f}", 'poolMedRtwo': f"{P['median_train_r2']:.2f}",
    'poolAdjRtwo': f"{P['mean_adj_r2']:.2f}",
    'poolWellfit': f"{P['n_wellfit']}", 'poolWellfitAgree': f"{P['agree_wellfit_pct']:.1f}",
    'rawMedianDeg': f"{P['model_vs_rawpeak_median_deg']:.1f}",
    'rawMedianDays': f"{days(P['model_vs_rawpeak_median_deg']):.0f}",
    'rawWithinSign': f"{P['model_vs_rawpeak_within_sign_pct']:.0f}",
    'rawAgree': f"{P['rawpeak_agree_pct']:.1f}",
    'rawPermZ': f"{P['rawpeak_perm_z']:.1f}",
    'rawPermP': ptex(P['rawpeak_perm_p']),
    'xTopics': f"{res['cross_property']['topics_in_multiple']}",
    'xPairs': f"{res['cross_property']['pairs']}",
    'xSame': f"{res['cross_property']['same_sign_pct']:.1f}",
}
for ds in DS:
    d = res[ds]; k = ds.replace("Topics", "")
    m[f'n{k}'] = f"{d['n']}"
    m[f'agree{k}'] = f"{d['agree_pct']:.1f}"
    m[f'permZ{k}'] = f"{d['perm_z']:.1f}"
    m[f'permP{k}'] = ptex(d['perm_p'])
    m[f'offset{k}'] = f"{d['mean_signed_offset_deg']:.1f}"
    m[f'rtwo{k}'] = f"{d['median_train_r2']:.2f}"
    m[f'rawAgree{k}'] = f"{d['rawpeak_agree_pct']:.1f}"
    m[f'rawZ{k}'] = f"{d['rawpeak_perm_z']:.1f}"
lines = ['%% AUTO-GENERATED by gen_numbers.py — do not edit by hand'] + [
    f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in m.items()]
open(os.path.join(HERE, 'numbers.tex'), 'w').write('\n'.join(lines) + '\n')
print(f"numbers.tex: {len(m)} macros (self-check passed)")
