#!/usr/bin/env python3
"""Build the repository's GitHub Pages site (docs/) — the campaign's public face, written for a
LAY READER (operator 2026-08-05: "very clear and explainable and concise and understandable by
layperson"). Every technical term is either translated or cut; the numbers keep their honesty.
Regenerated by this script; never hand-edit docs/index.html.

  python3 analysis/arxivtopics/build_docs.py
"""
import os, json, html, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DOCS = os.path.join(REPO, "docs")
os.makedirs(os.path.join(DOCS, "figs"), exist_ok=True)
for f in ("trend_binary_scatter.png", "trend_binary_controls.png", "fit_multiples.png"):
    shutil.copyfile(os.path.join(HERE, "figs", f), os.path.join(DOCS, "figs", f))

GP = json.load(open(os.path.join(HERE, "global_phasor.json")))
TB = json.load(open(os.path.join(HERE, "trend_binary.json")))
CT = json.load(open(os.path.join(HERE, "trend_binary_controls.json")))
S = TB["summary"]
above = sum(1 for v in TB["topics"].values() if v["test"] > 0.5)
ntop = len(TB["topics"])
rows = sorted(TB["topics"].items(), key=lambda kv: (-kv[1]["call_now"], -kv[1]["test"]))
trow = "\n".join(
    f"<tr><td>{html.escape(k)}</td><td class='n'>{'yes' if v['call_now'] else 'no'}</td>"
    f"<td class='n'>{int(round(v['test']*100))}%</td></tr>" for k, v in rows)
fast = CT["fast only (mars, jupiter)"]; slow = CT["slow only (ur, ne, pl)"]; year = CT["bare linear year [1, t]"]
gp_mean = sum(GP["gain"]) / len(GP["gain"])
gp_1996 = GP["gain"][-1]
arrows = " · ".join(f"{k} {v:.3f}" for k, v in GP["global_a"].items())

page = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>artatopics — results</title>
<style>
:root {{ --gold:#8A6D0B; --blue:#1746DC; --bg:#ffffff; --card:#f6f7f9; --ink:#1a2330; --ink2:#4a5568; --ink3:#6b7686; --line:#e3e6ea; }}
@media (prefers-color-scheme: dark) {{
  :root {{ --gold:#E8B923; --blue:#6f8dff; --bg:#010C17; --card:#06121E; --ink:#eef2f7; --ink2:#b8c2cf; --ink3:#8b98a8; --line:#12283c; }} }}
* {{ box-sizing:border-box }} body {{ margin:0; background:var(--bg); color:var(--ink);
  font:15px/1.55 -apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif }}
main {{ max-width:720px; margin:0 auto; padding:36px 20px 70px }}
h1 {{ font-size:26px; margin:0 }} h1 b {{ color:var(--gold) }}
h2 {{ font-size:16px; margin:34px 0 8px }}
p {{ color:var(--ink2); margin:8px 0 }}
table {{ border-collapse:collapse; width:100%; font-size:14px }}
th,td {{ text-align:left; padding:6px 10px; border-bottom:1px solid var(--line) }}
th {{ color:var(--ink3); font-size:11px; text-transform:uppercase; letter-spacing:.08em }}
td.n {{ font-variant-numeric:tabular-nums }}
.tiles {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; margin:12px 0 }}
.tile {{ background:var(--card); border:1px solid var(--line); border-radius:12px; padding:10px 13px }}
.tile .l {{ font-size:10.5px; text-transform:uppercase; letter-spacing:.1em; color:var(--ink3) }}
.tile .v {{ font-size:22px; font-weight:700; margin-top:2px }}
.tile .h {{ font-size:11.5px; color:var(--ink3); margin-top:2px; line-height:1.35 }}
img {{ max-width:100%; border-radius:10px; border:1px solid var(--line); background:#fff; margin-top:6px }}
input {{ width:100%; padding:8px 12px; border-radius:10px; border:1px solid var(--line);
  background:var(--card); color:var(--ink); font-size:14px; margin:6px 0 4px }}
a {{ color:var(--blue) }}
.wrap {{ overflow-x:auto; max-height:440px; overflow-y:auto; border:1px solid var(--line); border-radius:10px }}
.cap {{ font-size:12.5px; color:var(--ink3); margin:4px 0 0 }}
footer {{ margin-top:44px; font-size:12.5px; color:var(--ink3) }}
</style></head><body><main>

<h1>arta<b>topics</b></h1>
<p>Forecasting 251 research fields from planetary positions only. Every test: fit on data ≤1995,
graded on 1996–2025 the model never saw, against do-nothing baselines. Scores: 1.0 = perfect, 0 = no
better than the field's long-run average. Full code and data:
<a href="https://github.com/ArtaQuest/artatopics">github.com/ArtaQuest/artatopics</a>.</p>

<h2>1 · The deployed model — one receiver for all of science</h2>
<p style="font-family:ui-monospace,Menlo,monospace;background:var(--card);border:1px solid var(--line);border-radius:10px;padding:10px 14px;overflow-x:auto">
y_field(t) = | b<sub>field</sub> + A<sub>field</sub> &Sigma;<sub>i</sub> a<sub>i</sub> · e<sup> i(&theta;<sub>i</sub>(t) − p<sub>field,i</sub>)</sup> |²</p>
<p><b>What each symbol is.</b> θ<sub>i</sub>(t) is the position of planet i (Mars, Jupiter,
Saturn, Uranus, Neptune, Pluto, lunar node) in year t — known centuries ahead, which is the only
reason a thirty-year forecast is possible at all. Each planet contributes an arrow rotating in the
plane at its own orbital rate. The arrow lengths a<sub>i</sub> are <b>global</b>: one spectrum,
shared by every one of the 251 fields. A field owns exactly three personal things: a level
<b>b</b> (its resting brightness), a gain <b>A</b> (how loudly it hears the shared spectrum), and
seven phases <b>p<sub>i</sub></b> — where each planet must stand to push it hardest. The phases are
the field's identity — its signs. The predicted share is the squared length of the total arrow:
bright when the planets gang up on the field's phases, dim when they cancel.</p>
<p><b>Why the square matters.</b> Squaring the total arrow expands exactly — not approximately —
into a baseline, seven <b>transit</b> terms (2bA·a<sub>i</sub>·cos(θ<sub>i</sub>−p<sub>i</sub>), one
planet crossing the field's phase) and twenty-one <b>aspect</b> terms (2A²a<sub>i</sub>a<sub>k</sub>
times the cosine of the pair's separation against the pair's phases). Those are linear in fixed
functions of the date, so the model fits by least squares in closed form — no optimiser, no random
seed; refit it anywhere and the same numbers come out. The per-field level and gain then solve
exactly too: each is the root of a cubic. Two footnotes the fit forced on us, kept in the code: the
slowest features barely move inside a 296-year window, so a small ridge (chosen on early origins
only) is needed to keep the coefficients identifiable; and scale is each field's own historical
level — measured from its data, never fitted.</p>
<p><b>How it is tested.</b> Fit on everything up to 1995; forecast 1996–2025 blind; score against
carrying the field's average forward — and repeat from twelve different cut-off years so no single
lucky window decides anything. The same discipline as every number on this page.</p>
<div class="tiles">
<div class="tile"><div class="l">this model · 30 yr</div><div class="v">{gp_1996:.2f}</div><div class="h">fit ≤1995, graded 1996–2025</div></div>
<div class="tile"><div class="l">twelve origins, mean</div><div class="v">{gp_mean:.2f}</div><div class="h">"no change" scores 0.85</div></div>
<div class="tile"><div class="l">global parameters</div><div class="v">7</div><div class="h">the seven arrow lengths</div></div>
<div class="tile"><div class="l">per field</div><div class="v">9</div><div class="h">level + gain + seven phases</div></div>
</div>
<p class="cap">The global arrows: {arrows}. Honest comparison: the best per-field model in this
repository (each field also fitting its own arrow lengths) scores 0.88 / 0.80 on the same tests, and
"carry today forward" scores 0.85 / 0.73 — this model beats carry-forward at the 30-year wall.</p>

<h3 style="font-size:15px;margin:22px 0 6px">The data and the fit</h3>
<p><img src="figs/fit_multiples.png" alt="Six fields: actual citation share in blue, the deployed model in gold, fitted left of the dotted line, forecast to the right"></p>
<p class="cap">Blue = the field's actual share of each year's citations. Gold = this model: solid
where it was fitted (≤1995), dashed where it forecasts. The 8% Artificial Intelligence spike in 1868
is real data but thin evidence — 369 citations existed that year in total — and carries almost no
weight in the fit.</p>
<p>Every field, same picture:</p>
<select id="fieldpick" style="width:100%;padding:8px 12px;border-radius:10px;border:1px solid var(--line);background:var(--card);color:var(--ink);font-size:14px;margin:4px 0 6px"></select>
<div style="position:relative">
<svg id="fitchart" viewBox="0 0 720 260" style="width:100%;background:var(--card);border:1px solid var(--line);border-radius:10px"></svg>
<div id="tip" style="position:absolute;display:none;background:var(--bg);border:1px solid var(--line);border-radius:8px;padding:4px 8px;font-size:12px;pointer-events:none"></div>
</div>
<p class="cap" id="chartcap"></p>
<script src="series.js"></script>
<script>
(() => {{
  const sel = document.getElementById("fieldpick"), svg = document.getElementById("fitchart"),
        tip = document.getElementById("tip"), cap = document.getElementById("chartcap");
  Object.keys(SERIES).sort().forEach(k => {{ const o = document.createElement("option"); o.textContent = k; sel.appendChild(o); }});
  const css = v => getComputedStyle(document.documentElement).getPropertyValue(v).trim();
  function draw(name) {{
    const d = SERIES[name], W = 720, H = 260, L = 44, R = 8, T = 10, Bm = 24;
    const nA = d.actual.length, nM = d.model.length;
    const ymax = Math.max(...d.actual, ...d.model) * 1.05 || 1;
    const x = i => L + (W - L - R) * i / (nM - 1);
    const y = v => T + (H - T - Bm) * (1 - v / ymax);
    const path = (arr, i0, i1) => arr.slice(i0, i1 + 1).map((v, k) => (k ? "L" : "M") + x(i0 + k).toFixed(1) + " " + y(v).toFixed(1)).join("");
    const blue = css("--blue"), gold = css("--gold"), mut = css("--ink3"), lin = css("--line");
    let g = "";
    for (let f = 0; f <= 4; f++) {{ const yy = T + (H - T - Bm) * f / 4;
      g += `<line x1="${{L}}" y1="${{yy}}" x2="${{W - R}}" y2="${{yy}}" stroke="${{lin}}" stroke-width="1"/>`;
      g += `<text x="${{L - 6}}" y="${{yy + 4}}" fill="${{mut}}" font-size="10" text-anchor="end">${{(ymax * (1 - f / 4)).toFixed(1)}}</text>`; }}
    for (let yr = Math.ceil(d.y0 / 25) * 25; yr <= d.y0 + nM; yr += 25) {{ const xx = x(yr - d.y0);
      g += `<text x="${{xx}}" y="${{H - 8}}" fill="${{mut}}" font-size="10" text-anchor="middle">${{yr}}</text>`; }}
    const xw = x(d.wall);
    g += `<line x1="${{xw}}" y1="${{T}}" x2="${{xw}}" y2="${{H - Bm}}" stroke="${{mut}}" stroke-width="1" stroke-dasharray="2 3"/>`;
    g += `<path d="${{path(d.model, 0, d.wall)}}" fill="none" stroke="${{gold}}" stroke-width="2"/>`;
    g += `<path d="${{path(d.model, d.wall, nM - 1)}}" fill="none" stroke="${{gold}}" stroke-width="2" stroke-dasharray="5 4"/>`;
    g += `<path d="${{path(d.actual, 0, nA - 1)}}" fill="none" stroke="${{blue}}" stroke-width="1.6"/>`;
    g += `<line id="xh" y1="${{T}}" y2="${{H - Bm}}" stroke="${{mut}}" stroke-width="1" opacity="0"/>`;
    svg.innerHTML = g;
    cap.textContent = "share of each year's citations (%) · fitted ≤1995, forecast to " + (d.y0 + nM - 1);
    svg.onmousemove = ev => {{
      const r = svg.getBoundingClientRect(), mx = (ev.clientX - r.left) * W / r.width;
      const i = Math.max(0, Math.min(nM - 1, Math.round((mx - L) / (W - L - R) * (nM - 1))));
      const xh = svg.querySelector("#xh"); xh.setAttribute("x1", x(i)); xh.setAttribute("x2", x(i)); xh.setAttribute("opacity", .5);
      tip.style.display = "block"; tip.style.left = Math.min(ev.clientX - r.left + 12, r.width - 150) + "px"; tip.style.top = "8px";
      tip.innerHTML = (d.y0 + i) + " · model " + d.model[i].toFixed(2) + "%" + (i < nA ? " · actual " + d.actual[i].toFixed(2) + "%" : " (forecast)");
    }};
    svg.onmouseleave = () => {{ tip.style.display = "none"; svg.querySelector("#xh").setAttribute("opacity", 0); }};
  }}
  sel.onchange = () => draw(sel.value);
  sel.value = "Artificial Intelligence"; draw(sel.value);
}})();
</script>

<h2>2 · The per-field reference model, 30-year forecast</h2>
<div class="tiles">
<div class="tile"><div class="l">model · 30 yr</div><div class="v">0.80</div><div class="h">9 parameters per field</div></div>
<div class="tile"><div class="l">"no change" · 30 yr</div><div class="v">0.73</div><div class="h">carry today forward</div></div>
<div class="tile"><div class="l">model · 12 yr</div><div class="v">0.93</div><div class="h"></div></div>
<div class="tile"><div class="l">model · 4 yr</div><div class="v">0.97</div><div class="h"></div></div>
</div>

<h2>3 · The share of attention across all fields at once</h2>
<table><tr><th>strategy</th><th>error ↓</th></tr>
<tr><td>copy yesterday's distribution</td><td class="n"><b>0.083</b></td></tr>
<tr><td>per-field model, renormalised</td><td class="n">0.085</td></tr>
<tr><td>best combined planet model</td><td class="n">0.088</td></tr>
<tr><td>softmax (convex, provably optimal)</td><td class="n">0.110</td></tr></table>
<p class="cap">Copying yesterday wins. Fields drift one way (AI grows, old fields shrink); periodic
signals cannot encode drift. Verified not to be a training issue: loss, model form, phase count and
topic roster all varied — ranking unchanged.</p>

<h2>4 · "Will it trend next year?" — one predictor per field, trained by least squares, called at the field's median</h2>
<div class="tiles">
<div class="tile"><div class="l">unseen data</div><div class="v">{S["test_mean"]*100:.0f}%</div><div class="h">balanced · coin flip = 50%</div></div>
<div class="tile"><div class="l">fields above chance</div><div class="v">{above*100//ntop}%</div><div class="h">{above} of {ntop}</div></div>
<div class="tile"><div class="l">latest-years test</div><div class="v">{S["test_temporal_mean"]*100:.0f}%</div><div class="h"></div></div>
</div>
<p><b>Controls:</b> fast planets only → {fast["shuffled"]*100:.0f}% (chance). Slow planets only →
{slow["shuffled"]*100:.0f}%. Calendar year alone → {year["shuffled"]*100:.0f}%, better than the sky.
The accuracy is calendar signal carried by the slow planets, not planetary rhythm.</p>
<img src="figs/trend_binary_controls.png" alt="Controls: fast planets at chance; slow planets carry the accuracy; a bare year does best">

<h2>Per-field calls</h2>
<input id="q" placeholder="filter fields…" oninput="
  const v=this.value.toLowerCase();
  document.querySelectorAll('#tt tbody tr').forEach(r=>r.style.display=r.cells[0].textContent.toLowerCase().includes(v)?'':'none');">
<div class="wrap"><table id="tt"><thead><tr><th>field</th><th>call</th><th>accuracy</th></tr></thead>
<tbody>{trow}</tbody></table></div>

<h2>5 · The competition — four GPU model families vs two do-nothing baselines</h2>
<p>The whole campaign was then run as an open benchmark: a public Kaggle dataset, four competing
model families trained on separate GPU accounts, scored blind on the ArtaQuest platform. Best
selected model: a stack blending a damped trend with the sky receiver above (−2.09); a plain
damped trend scores −2.04; every single-family GPU model loses to the baselines. The full board,
the era-shift finding behind it, and a lab that rebuilds the winner in your browser (Pyodide):
<a href="ensemble.html"><b>the ensemble stack →</b></a></p>

<footer>No causal claims. Code MIT · data CC0 (OpenAlex) ·
<a href="https://github.com/ArtaQuest/artatopics">source</a></footer>
</main></body></html>"""
open(os.path.join(DOCS, "index.html"), "w").write(page)
print(f"docs/index.html written ({len(page)//1024}KB)")
