#!/usr/bin/env python3
"""Build the repository's GitHub Pages site (docs/) — the campaign's public face, written for a
LAY READER (operator 2026-08-05: "very clear and explainable and concise and understandable by
layperson"). Every technical term is either translated or cut; the numbers keep their honesty.
Regenerated by this script; never hand-edit docs/index.html.

  python3 analysis/arxivtopics/build_docs.py
"""
import os, json, html, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DOCS = os.path.join(REPO, "docs")
os.makedirs(os.path.join(DOCS, "figs"), exist_ok=True)
for f in ("trend_binary_scatter.png", "trend_binary_controls.png"):
    shutil.copyfile(os.path.join(HERE, "figs", f), os.path.join(DOCS, "figs", f))

TB = json.load(open(os.path.join(HERE, "trend_binary.json")))
rows = sorted(TB["topics"].items(), key=lambda kv: -kv[1]["p_now"])
S = TB["summary"]

trow = "\n".join(
    f"<tr><td>{html.escape(k)}</td><td class='n'>{int(round(v['p_now']*100))}%</td>"
    f"<td class='n'>{'yes' if v['p_now'] >= 0.5 else 'no'}</td><td class='n'>{int(round(v['test']*100))}%</td></tr>"
    for k, v in rows)

page = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>artatopics — results</title>
<style>
:root {{ --gold:#8A6D0B; --blue:#1746DC; --bg:#ffffff; --card:#f6f7f9; --ink:#1a2330; --ink2:#4a5568; --ink3:#6b7686; --line:#e3e6ea; }}
@media (prefers-color-scheme: dark) {{
  :root {{ --gold:#E8B923; --blue:#6f8dff; --bg:#010C17; --card:#06121E; --ink:#eef2f7; --ink2:#b8c2cf; --ink3:#8b98a8; --line:#12283c; }} }}
* {{ box-sizing:border-box }} body {{ margin:0; background:var(--bg); color:var(--ink);
  font:15px/1.55 -apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif }}
main {{ max-width:720px; margin:0 auto; padding:36px 20px 70px }}
h1 {{ font-size:26px; margin:0 }} h1 b {{ color:var(--gold) }}
h2 {{ font-size:16px; margin:34px 0 8px }}
p {{ color:var(--ink2); margin:8px 0 }}
table {{ border-collapse:collapse; width:100%; font-size:14px }}
th,td {{ text-align:left; padding:6px 10px; border-bottom:1px solid var(--line) }}
th {{ color:var(--ink3); font-size:11px; text-transform:uppercase; letter-spacing:.08em }}
td.n {{ font-variant-numeric:tabular-nums }}
.tiles {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; margin:12px 0 }}
.tile {{ background:var(--card); border:1px solid var(--line); border-radius:12px; padding:10px 13px }}
.tile .l {{ font-size:10.5px; text-transform:uppercase; letter-spacing:.1em; color:var(--ink3) }}
.tile .v {{ font-size:22px; font-weight:700; margin-top:2px }}
.tile .h {{ font-size:11.5px; color:var(--ink3); margin-top:2px; line-height:1.35 }}
img {{ max-width:100%; border-radius:10px; border:1px solid var(--line); background:#fff; margin-top:6px }}
input {{ width:100%; padding:8px 12px; border-radius:10px; border:1px solid var(--line);
  background:var(--card); color:var(--ink); font-size:14px; margin:6px 0 4px }}
a {{ color:var(--blue) }}
.wrap {{ overflow-x:auto; max-height:440px; overflow-y:auto; border:1px solid var(--line); border-radius:10px }}
.cap {{ font-size:12.5px; color:var(--ink3); margin:4px 0 0 }}
footer {{ margin-top:44px; font-size:12.5px; color:var(--ink3) }}
</style></head><body><main>

<h1>arta<b>topics</b></h1>
<p>Forecasting 251 research fields from planetary positions only. Every test: fit on data ≤1995,
graded on 1996–2025 the model never saw, against do-nothing baselines. Scores: 1.0 = perfect, 0 = no
better than the field's long-run average. Full code and data:
<a href="https://github.com/ArtaQuest/artatopics">github.com/ArtaQuest/artatopics</a>.</p>

<h2>1 · Per-field 30-year forecast</h2>
<div class="tiles">
<div class="tile"><div class="l">model · 30 yr</div><div class="v">0.80</div><div class="h">9 parameters per field</div></div>
<div class="tile"><div class="l">"no change" · 30 yr</div><div class="v">0.73</div><div class="h">carry today forward</div></div>
<div class="tile"><div class="l">model · 12 yr</div><div class="v">0.93</div><div class="h"></div></div>
<div class="tile"><div class="l">model · 4 yr</div><div class="v">0.97</div><div class="h"></div></div>
</div>

<h2>2 · The share of attention across all fields at once</h2>
<table><tr><th>strategy</th><th>error ↓</th></tr>
<tr><td>copy yesterday's distribution</td><td class="n"><b>0.083</b></td></tr>
<tr><td>per-field model, renormalised</td><td class="n">0.085</td></tr>
<tr><td>best combined planet model</td><td class="n">0.088</td></tr>
<tr><td>softmax (convex, provably optimal)</td><td class="n">0.110</td></tr></table>
<p class="cap">Copying yesterday wins. Fields drift one way (AI grows, old fields shrink); periodic
signals cannot encode drift. Verified not to be a training issue: loss, model form, phase count and
topic roster all varied — ranking unchanged.</p>

<h2>3 · "Will it trend next year?" — one yes/no predictor per field</h2>
<div class="tiles">
<div class="tile"><div class="l">unseen data</div><div class="v">{S["test_mean"]*100:.0f}%</div><div class="h">coin flip = 50%</div></div>
<div class="tile"><div class="l">fields above chance</div><div class="v">89%</div><div class="h">223 of 251</div></div>
<div class="tile"><div class="l">latest-years test</div><div class="v">{S["test_temporal_mean"]*100:.0f}%</div><div class="h"></div></div>
</div>
<p><b>Controls:</b> fast planets only → 48% (chance). Slow planets only → 70%. Calendar year alone →
71–73%, better than the sky. The accuracy is calendar signal carried by the slow planets, not
planetary rhythm.</p>
<img src="figs/trend_binary_controls.png" alt="Controls: fast planets at chance; slow planets carry the accuracy; a bare year does best">
<img src="figs/trend_binary_scatter.png" alt="Per-field train vs held-out accuracy; most fields above the 0.5 chance line">

<h2>Per-field calls</h2>
<input id="q" placeholder="filter fields…" oninput="
  const v=this.value.toLowerCase();
  document.querySelectorAll('#tt tbody tr').forEach(r=>r.style.display=r.cells[0].textContent.toLowerCase().includes(v)?'':'none');">
<div class="wrap"><table id="tt"><thead><tr><th>field</th><th>p(trend)</th><th>call</th><th>accuracy</th></tr></thead>
<tbody>{trow}</tbody></table></div>

<footer>No causal claims. Code MIT · data CC0 (OpenAlex) ·
<a href="https://github.com/ArtaQuest/artatopics">source</a></footer>
</main></body></html>"""
open(os.path.join(DOCS, "index.html"), "w").write(page)
print(f"docs/index.html written ({len(page)//1024}KB)")
