#!/usr/bin/env python3
"""Build the repository's GitHub Pages site (docs/) — the campaign's public face, written for a
LAY READER (operator 2026-08-05: "very clear and explainable and concise and understandable by
layperson"). Every technical term is either translated or cut; the numbers keep their honesty.
Regenerated by this script; never hand-edit docs/index.html.

  python3 analysis/arxivtopics/build_docs.py
"""
import os, json, html, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DOCS = os.path.join(REPO, "docs")
os.makedirs(os.path.join(DOCS, "figs"), exist_ok=True)
for f in ("trend_binary_scatter.png", "trend_binary_controls.png"):
    shutil.copyfile(os.path.join(HERE, "figs", f), os.path.join(DOCS, "figs", f))

GP = json.load(open(os.path.join(HERE, "global_phasor.json")))
TB = json.load(open(os.path.join(HERE, "trend_binary.json")))
CT = json.load(open(os.path.join(HERE, "trend_binary_controls.json")))
S = TB["summary"]
above = sum(1 for v in TB["topics"].values() if v["test"] > 0.5)
ntop = len(TB["topics"])
rows = sorted(TB["topics"].items(), key=lambda kv: (-kv[1]["call_now"], -kv[1]["test"]))
trow = "\n".join(
    f"<tr><td>{html.escape(k)}</td><td class='n'>{'yes' if v['call_now'] else 'no'}</td>"
    f"<td class='n'>{int(round(v['test']*100))}%</td></tr>" for k, v in rows)
fast = CT["fast only (mars, jupiter)"]; slow = CT["slow only (ur, ne, pl)"]; year = CT["bare linear year [1, t]"]
gp_mean = sum(GP["exact_global"]) / len(GP["exact_global"])
gp_1996 = GP["exact_global"][-1]
arrows = " · ".join(f"{k} {v:.3f}" for k, v in GP["global_a"].items())

page = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>artatopics — results</title>
<style>
:root {{ --gold:#8A6D0B; --blue:#1746DC; --bg:#ffffff; --card:#f6f7f9; --ink:#1a2330; --ink2:#4a5568; --ink3:#6b7686; --line:#e3e6ea; }}
@media (prefers-color-scheme: dark) {{
  :root {{ --gold:#E8B923; --blue:#6f8dff; --bg:#010C17; --card:#06121E; --ink:#eef2f7; --ink2:#b8c2cf; --ink3:#8b98a8; --line:#12283c; }} }}
* {{ box-sizing:border-box }} body {{ margin:0; background:var(--bg); color:var(--ink);
  font:15px/1.55 -apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif }}
main {{ max-width:720px; margin:0 auto; padding:36px 20px 70px }}
h1 {{ font-size:26px; margin:0 }} h1 b {{ color:var(--gold) }}
h2 {{ font-size:16px; margin:34px 0 8px }}
p {{ color:var(--ink2); margin:8px 0 }}
table {{ border-collapse:collapse; width:100%; font-size:14px }}
th,td {{ text-align:left; padding:6px 10px; border-bottom:1px solid var(--line) }}
th {{ color:var(--ink3); font-size:11px; text-transform:uppercase; letter-spacing:.08em }}
td.n {{ font-variant-numeric:tabular-nums }}
.tiles {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; margin:12px 0 }}
.tile {{ background:var(--card); border:1px solid var(--line); border-radius:12px; padding:10px 13px }}
.tile .l {{ font-size:10.5px; text-transform:uppercase; letter-spacing:.1em; color:var(--ink3) }}
.tile .v {{ font-size:22px; font-weight:700; margin-top:2px }}
.tile .h {{ font-size:11.5px; color:var(--ink3); margin-top:2px; line-height:1.35 }}
img {{ max-width:100%; border-radius:10px; border:1px solid var(--line); background:#fff; margin-top:6px }}
input {{ width:100%; padding:8px 12px; border-radius:10px; border:1px solid var(--line);
  background:var(--card); color:var(--ink); font-size:14px; margin:6px 0 4px }}
a {{ color:var(--blue) }}
.wrap {{ overflow-x:auto; max-height:440px; overflow-y:auto; border:1px solid var(--line); border-radius:10px }}
.cap {{ font-size:12.5px; color:var(--ink3); margin:4px 0 0 }}
footer {{ margin-top:44px; font-size:12.5px; color:var(--ink3) }}
</style></head><body><main>

<h1>arta<b>topics</b></h1>
<p>Forecasting 251 research fields from planetary positions only. Every test: fit on data ≤1995,
graded on 1996–2025 the model never saw, against do-nothing baselines. Scores: 1.0 = perfect, 0 = no
better than the field's long-run average. Full code and data:
<a href="https://github.com/ArtaQuest/artatopics">github.com/ArtaQuest/artatopics</a>.</p>

<h2>1 · The deployed model — one receiver for all of science</h2>
<p style="font-family:ui-monospace,Menlo,monospace;background:var(--card);border:1px solid var(--line);border-radius:10px;padding:10px 14px;overflow-x:auto">
y_field(t) = | b + &Sigma;<sub>i</sub> a<sub>i</sub> · e<sup> i(&theta;<sub>i</sub>(t) − p<sub>field,i</sub>)</sup> |²</p>
<p>Each planet is an arrow spinning at its orbital rate. The level <b>b</b> and the seven arrow
lengths <b>a<sub>i</sub></b> are <b>global</b> — one receiver shared by all 251 fields. A field owns
nothing but its seven phases — its signs. Squaring the total arrow's length expands exactly into a
baseline, seven <b>transit</b> terms (each planet crossing the field's phase) and twenty-one
<b>aspect</b> terms (planet pairs) — all linear in fixed functions of the date, so the whole fit is
closed-form least squares: no optimiser, no seed. Scale is each field's own historical level —
measured, not fitted.</p>
<div class="tiles">
<div class="tile"><div class="l">this model · 30 yr</div><div class="v">{gp_1996:.2f}</div><div class="h">fit ≤1995, graded 1996–2025</div></div>
<div class="tile"><div class="l">twelve origins, mean</div><div class="v">{gp_mean:.2f}</div><div class="h">"no change" scores 0.85</div></div>
<div class="tile"><div class="l">global parameters</div><div class="v">8</div><div class="h">b = {GP["global_b"]:.2f} + seven arrows</div></div>
<div class="tile"><div class="l">per field</div><div class="v">7</div><div class="h">phases only — the field's signs</div></div>
</div>
<p class="cap">The global arrows: {arrows}. Honest comparison: the best per-field model in this
repository (each field also fitting its own arrow lengths) scores 0.88 / 0.80 on the same tests —
the price of one shared receiver is about 0.06. Both sit below "copy yesterday" on the twelve-origin
mean; at the 30-year wall this model ties it (0.73).</p>

<h2>2 · The per-field reference model, 30-year forecast</h2>
<div class="tiles">
<div class="tile"><div class="l">model · 30 yr</div><div class="v">0.80</div><div class="h">9 parameters per field</div></div>
<div class="tile"><div class="l">"no change" · 30 yr</div><div class="v">0.73</div><div class="h">carry today forward</div></div>
<div class="tile"><div class="l">model · 12 yr</div><div class="v">0.93</div><div class="h"></div></div>
<div class="tile"><div class="l">model · 4 yr</div><div class="v">0.97</div><div class="h"></div></div>
</div>

<h2>3 · The share of attention across all fields at once</h2>
<table><tr><th>strategy</th><th>error ↓</th></tr>
<tr><td>copy yesterday's distribution</td><td class="n"><b>0.083</b></td></tr>
<tr><td>per-field model, renormalised</td><td class="n">0.085</td></tr>
<tr><td>best combined planet model</td><td class="n">0.088</td></tr>
<tr><td>softmax (convex, provably optimal)</td><td class="n">0.110</td></tr></table>
<p class="cap">Copying yesterday wins. Fields drift one way (AI grows, old fields shrink); periodic
signals cannot encode drift. Verified not to be a training issue: loss, model form, phase count and
topic roster all varied — ranking unchanged.</p>

<h2>4 · "Will it trend next year?" — one predictor per field, trained by least squares, called at the field's median</h2>
<div class="tiles">
<div class="tile"><div class="l">unseen data</div><div class="v">{S["test_mean"]*100:.0f}%</div><div class="h">balanced · coin flip = 50%</div></div>
<div class="tile"><div class="l">fields above chance</div><div class="v">{above*100//ntop}%</div><div class="h">{above} of {ntop}</div></div>
<div class="tile"><div class="l">latest-years test</div><div class="v">{S["test_temporal_mean"]*100:.0f}%</div><div class="h"></div></div>
</div>
<p><b>Controls:</b> fast planets only → {fast["shuffled"]*100:.0f}% (chance). Slow planets only →
{slow["shuffled"]*100:.0f}%. Calendar year alone → {year["shuffled"]*100:.0f}%, better than the sky.
The accuracy is calendar signal carried by the slow planets, not planetary rhythm.</p>
<img src="figs/trend_binary_controls.png" alt="Controls: fast planets at chance; slow planets carry the accuracy; a bare year does best">

<h2>Per-field calls</h2>
<input id="q" placeholder="filter fields…" oninput="
  const v=this.value.toLowerCase();
  document.querySelectorAll('#tt tbody tr').forEach(r=>r.style.display=r.cells[0].textContent.toLowerCase().includes(v)?'':'none');">
<div class="wrap"><table id="tt"><thead><tr><th>field</th><th>call</th><th>accuracy</th></tr></thead>
<tbody>{trow}</tbody></table></div>

<footer>No causal claims. Code MIT · data CC0 (OpenAlex) ·
<a href="https://github.com/ArtaQuest/artatopics">source</a></footer>
</main></body></html>"""
open(os.path.join(DOCS, "index.html"), "w").write(page)
print(f"docs/index.html written ({len(page)//1024}KB)")
